version: '3.9'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - migrate
  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
volumes:
  static_volume: 